apiVersion: v1
kind: Service
metadata:
  name: flask-web-service
spec:
  type: NodePort
  selector:
    app: flask-web-app
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30040 # You can access the app at http://<Server-IP>:30040